PracaInzynierska/PracaInzynierska/Components/CartNavigationViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PracaInzynierska.Infrastructure;
using PracaInzynierska.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracaInzynierska.Components
{
    public class CartNavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<CartProductViewModel> cartProducts= new List<CartProductViewModel>();
            int quantity = 0;

            if (HttpContext.Session.GetString(Constans.SessionCartKey) != null)
            {
                cartProducts = HttpContext.Session.GetObjectFromJson<List<CartProductViewModel>>(Constans.SessionCartKey);

                 quantity = cartProducts.Sum(x => x.Quantity);
            }

            return View(quantity);
        }
    }
}

PracaInzynierska/PracaInzynierska/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PracaInzynierska.Data;

namespace PracaInzynierska.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProductController(ApplicationDbContext applicationDbContext)
        {
            _db = applicationDbContext;
        }

        public ActionResult Categories()
        {
            var categories = _db.Categories.ToList();

            return View(categories);
        }

        public ActionResult Products(string category = "")
        {

            if (category == "")
            {
                var allProducts = _db.Products
                    .Where(x => !x.Hidden)
                    .ToList();

                return View(allProducts);
            }

            var products = _db.Products
                .Where(x => x.Category.Name == category && !x.Hidden)
                .ToList();

            return View(products);
        }

        public ActionResult Description(int id)
        {

            var product = _db.Products
                 .Where(x => x.ProductId == id)
                 .FirstOrDefault();

            return View(product);
        }
    }
}

PracaInzynierska/PracaInzynierska/Views/Shared/_Layout.cshtml
@using PracaInzynierska.Infrastructure;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracaInzynierska</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar bg-danger navbar-dark navbar-expand-md ">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-hamburger"></i> Restauracja</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Przycisk nawigacyjny">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Categories">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>*@
                    <li class="nav-item">
                        @await Component.InvokeAsync("CartNavigation")
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <partial name="_LoginPartial" />
                    <li>
                        <a class="nav-link" href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a>
                    </li>
                    <li>
                        <a class="nav-link" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a class="nav-link" href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
        <img src=@Url.ImagePath("banner.jpeg") class="img-fluid mb-2" alt="Baner strony" />
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-copyright text-center bg-danger text-light p-4 mt-2">
        @DateTime.Now.Year - &copy;<a class="text-light" href="mailto:Restauracja@gmail.com">Restauracja@gmail.com</a>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>